const { Router } = require("express")
const sessions = require("./sessions")
const users = require("./users")
const arts = require("./arts")
const commissions = require("./commissions")

module.exports = Router()
  .use("/sessions", sessions)
  .use("/users", users)
  .use("/arts", arts)
  .use("/commissions", commissions)
