const { Router } = require("express")
const sessions = require("./sessions")
const users = require("./users")
const arts = require("./arts")
const commissions = require("./commissions")
const negotiations = require("./negotiations")
const chats = require("./chats")

module.exports = Router()
  .use("/sessions", sessions)
  .use("/users", users)
  .use("/arts", arts)
  .use("/commissions", commissions)
  .use("/commissions/:commissionId/negotiations", negotiations)
  .use("/commissions/:commissionId/negotiations/:artistId/chats", chats)
